Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,12 +25,20 @@ jobs:
             export PATH=$(pwd)/sonar-scanner-4.6.2.2472-linux/bin:$PATH
             echo $PATH
             ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner --version
+      - run:
+          name: Run SonarQube Scanner
+          command: |
+            ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
+              -Dsonar.projectKey=your_project_key \
+              -Dsonar.sources=. \
+              -Dsonar.host.url=https://sonarcloud.io \
+              -Dsonar.login=$SONAR_TOKEN || echo "SonarQube analysis failed, continuing..."
 
 workflows:
   version: 2
   main-workflow:
     jobs:
       - say-hello
-
+      - sonar_analysis:
           requires:
             - say-hello
